"""BlackRock-style XRP macro surveillance dashboard (patched).

This module provides a Streamlit-based dashboard for monitoring
XRP market telemetry, flows, sentiment and more. It is adapted
from the upstream code but with a number of improvements aimed at
modernising the refresh behaviour and database connectivity.

Key changes in this patched version include:

* Automatic page refresh without using the HTML meta refresh tag.  The
  original implementation injected a `<meta http-equiv="refresh">` tag
  into the page which caused a full browser reload.  This patch uses
  `streamlit_autorefresh` when available, or falls back to scheduling
  `st.experimental_rerun()` in a background thread.  This preserves
  session state and avoids jarring page reloads.
* Support for both classic and URL-based PostgreSQL connection strings via
  the updated `db.py` helper.  See that module for details.

This file was generated by merging the upstream `main.py` and applying
targeted modifications.  To ease auditing, the majority of the code
remains unchanged; look for comments marked with `# PATCH:` to locate
modifications.
"""

import math
import os
import importlib.util
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Tuple

import plotly.graph_objects as go
import requests
import streamlit as st

from app_utils import cache_get_json, normalize_env_value, safe_get
from redis_client import rdb
from signals import (
    SIGNAL_COMPONENTS,
    calibrated_conviction_probability,
    derive_reason_codes,
    log_score_components,
    reason_score_adjustment,
)

from db import fetch_latest_flow, fetch_latest_snapshot
from xrpl_utils import fetch_account_overview, parse_account_input

# PATCH: Additional imports for autorefresh fallback.
import threading
import time

# =========================
# Page config & styling
# =========================
st.set_page_config(
    page_title="XRP Quant Governance Console",
    layout="wide",
    initial_sidebar_state="collapsed",
)

PALETTE = {
    "bg": "#0b1021",
    "panel": "rgba(255, 255, 255, 0.04)",
    "accent": "#4ade80",
    "muted": "#9ca3af",
    "text": "#e5e7eb",
    "alert": "#f97316",
    "error": "#ef4444",
}

st.markdown(
    f"""
    <style>
    body {{background-color: {PALETTE['bg']}; color: {PALETTE['text']};}}
    .metric {{background:{PALETTE['panel']}; padding:14px 16px; border-radius:14px; border:1px solid rgba(255,255,255,0.06);}}
    .metric h3 {{font-size:14px; color:{PALETTE['muted']}; margin-bottom:6px; text-transform:uppercase; letter-spacing:0.08em;}}
    .metric .value {{font-size:26px; font-weight:700; color:{PALETTE['text']};}}
    .metric .note {{font-size:13px; color:{PALETTE['muted']}; margin-top:4px;}}
    .section-title {{font-size:18px; font-weight:700; letter-spacing:0.02em;}}
    .tag {{display:inline-block; padding:6px 10px; border-radius:999px; font-size:12px; margin-right:6px;}}
    .tag-ok {{background:rgba(74,222,128,0.14); color:#bbf7d0; border:1px solid rgba(74,222,128,0.5);}}
    .tag-warn {{background:rgba(249,115,22,0.16); color:#fed7aa; border:1px solid rgba(249,115,22,0.4);}}
    .tag-err {{background:rgba(239,68,68,0.16); color:#fecdd3; border:1px solid rgba(239,68,68,0.4);}}
    </style>
    """,
    unsafe_allow_html=True,
)

# =========================
# Helpers
# =========================

SESSION_FALLBACK: Dict[str, Any] = {}


def get_state(key: str, default: Any) -> Any:
    try:
        if key in st.session_state:
            return st.session_state.get(key, default)
    except Exception:  # noqa: BLE001
        pass
    return SESSION_FALLBACK.get(key, default)


def set_state(key: str, value: Any) -> None:
    SESSION_FALLBACK[key] = value
    try:
        st.session_state[key] = value
    except Exception:  # noqa: BLE001
        return


def redact_secret(value: str, keep: int = 4) -> str:
    if not value:
        return "<empty>"
    if len(value) <= keep * 2:
        return "*" * len(value)
    return f"{value[:keep]}***{value[-keep:]}"


def to_datetime(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except Exception:  # noqa: BLE001
        return None


def time_ago(ts: Optional[datetime]) -> str:
    if not ts:
        return "unknown"
    delta = datetime.now(timezone.utc) - ts
    if delta < timedelta(seconds=90):
        return f"{int(delta.total_seconds())}s ago"
    if delta < timedelta(hours=2):
        return f"{int(delta.total_seconds() // 60)}m ago"
    hours = int(delta.total_seconds() // 3600)
    return f"{hours}h ago"


def styled_metric(title: str, value: str, note: str = "") -> None:
    st.markdown(
        f"""
        <div class="metric">
            <h3>{title}</h3>
            <div class="value">{value}</div>
            <div class="note">{note}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _clamp(value: float, *, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, value))


def drops_to_xrp(value: Optional[float]) -> float:
    try:
        return float(value or 0.0) / 1_000_000
    except Exception:  # noqa: BLE001
        return 0.0


def compute_signal_stack(
    price: Dict[str, Optional[float]],
    futures: Dict[str, Optional[float]],
    flows: Dict[str, Any],
    sentiment: Dict[str, Any],
) -> Dict[str, Any]:
    """Translate raw telemetry into composite-ready signal contributions."""

    details: List[Dict[str, Any]] = []
    reason_inputs: Dict[str, Any] = {}
    prev_price = get_state("last_price", None)
    prev_agg_oi = get_state("last_agg_oi", None)

    def add_component(
        key: str,
        *,
        points: float,
        available: bool,
        status: str,
        note: str,
    ) -> None:
        meta = SIGNAL_COMPONENTS.get(key)
        max_points = meta.max_points if meta else 0.0
        details.append(
            {
                "key": key,
                "name": meta.name if meta else key,
                "points": max(0.0, min(points, max_points)),
                "max_points": max_points,
                "status": status,
                "note": note,
                "available": available,
                "cap_note": meta.cap_note if meta else "",
            }
        )

    price_usd = price.get("price")
    price_meta = SIGNAL_COMPONENTS.get("price_window")
    if price_usd is None:
        add_component(
            "price_window",
            points=0.0,
            available=False,
            status="Waiting on price feed",
            note="CoinGecko price missing; composite gated until price returns.",
        )
    else:
        if price_usd <= 2.45:
            price_points = price_meta.max_points
            status = "In breakout zone"
        elif price_usd >= 3.0:
            price_points = 0.0
            status = "Extended; patience warranted"
        else:
            scale = _clamp((3.0 - price_usd) / (3.0 - 2.45))
            price_points = price_meta.max_points * scale
            status = "Approaching extension"
        add_component(
            "price_window",
            points=price_points,
            available=True,
            status=status,
            note=f"${price_usd:,.4f} vs. $2.45–$3.00 window",
        )
        reason_inputs["price_status"] = status

    funding = futures.get("funding")
    fund_meta = SIGNAL_COMPONENTS.get("funding")
    if funding is None:
        add_component(
            "funding",
            points=0.0,
            available=False,
            status="Funding unavailable",
            note="Binance funding endpoint did not return data.",
        )
    else:
        funding_bps = funding * 10_000
        scaled = math.tanh(max(funding_bps, 0.0) / 10.0)
        funding_points = fund_meta.max_points * scaled
        status = "Bullish carry" if funding_bps > 0.5 else "Flat/neutral"
        add_component(
            "funding",
            points=funding_points,
            available=True,
            status=status,
            note=f"{funding_bps:+.2f} bps drift (tanh-capped)",
        )
        reason_inputs["funding_z_score"] = funding_bps / 5.0

    oi_usd = futures.get("open_interest")
    oi_meta = SIGNAL_COMPONENTS.get("oi")
    if oi_usd is None:
        add_component(
            "oi",
            points=0.0,
            available=False,
            status="OI missing",
            note="Open interest endpoint unavailable.",
        )
    else:
        depth_scale = _clamp((oi_usd - 1_500_000_000) / (2_700_000_000 - 1_500_000_000))
        oi_points = depth_scale * oi_meta.max_points
        status = "Depth supportive" if depth_scale >= 0.6 else "Shallow liquidity"
        add_component(
            "oi",
            points=oi_points,
            available=True,
            status=status,
            note=f"${oi_usd:,.0f} open interest vs. $1.5B–$2.7B lane",
        )

    agg_oi = futures.get("aggregated_open_interest")
    agg_meta = SIGNAL_COMPONENTS.get("oi_aggregated")
    if agg_meta:
        if agg_oi is None:
            add_component(
                "oi_aggregated",
                points=0.0,
                available=False,
                status="Aggregated OI missing",
                note="Could not fetch aggregated open interest across venues.",
            )
        else:
            agg_scale = _clamp((agg_oi - 2_000_000_000) / (4_000_000_000 - 2_000_000_000))
            agg_points = agg_meta.max_points * agg_scale
            status = "Depth supportive" if agg_scale >= 0.6 else "Shallow liquidity"
            add_component(
                "oi_aggregated",
                points=agg_points,
                available=True,
                status=status,
                note=f"${agg_oi:,.0f} aggregated OI",
            )

    rvol = futures.get("relative_volume")
    rvol_meta = SIGNAL_COMPONENTS.get("relative_volume")
    if rvol_meta:
        if rvol is None:
            add_component(
                "relative_volume",
                points=0.0,
                available=False,
                status="Volume unavailable",
                note="Could not compute relative volume; CoinGecko volume API missing.",
            )
        else:
            rvol_scale = _clamp((rvol - 1.0) / (3.0 - 1.0))
            rvol_points = rvol_meta.max_points * rvol_scale
            status = "High activity" if rvol >= 2.0 else "Average volume"
            add_component(
                "relative_volume",
                points=rvol_points,
                available=True,
                status=status,
                note=f"rVOL {rvol:.2f}",
            )

    oi_change_meta = SIGNAL_COMPONENTS.get("oi_change")
    if oi_change_meta:
        agg_oi = futures.get("aggregated_open_interest")
        last_agg = prev_agg_oi
        delta_oi: Optional[float] = None
        if agg_oi is not None and last_agg is not None:
            delta_oi = agg_oi - last_agg
        if delta_oi is None or agg_oi is None or last_agg is None:
            add_component(
                "oi_change",
                points=0.0,
                available=False,
                status="Change unavailable",
                note="Insufficient history to compute OI change.",
            )
        else:
            abs_delta = abs(delta_oi)
            change_scale = _clamp(abs_delta / 200_000_000.0)
            change_points = oi_change_meta.max_points * change_scale
            status = "Increasing OI" if delta_oi > 0 else "Decreasing OI"
            add_component(
                "oi_change",
                points=change_points,
                available=True,
                status=status,
                note=f"{delta_oi:,.0f} change vs. last snapshot",
            )
            reason_inputs["oi_direction"] = "up" if delta_oi > 0 else "down"

    div_meta = SIGNAL_COMPONENTS.get("divergence")
    if div_meta:
        agg_oi = futures.get("aggregated_open_interest")
        last_agg = prev_agg_oi
        price_now = price.get("price")
        last_price = prev_price
        divergence_detected = False
        if agg_oi is not None and last_agg is not None and price_now is not None and last_price is not None:
            delta_oi = agg_oi - last_agg
            delta_price = price_now - last_price
            if delta_oi > 0 and delta_price < 0:
                divergence_detected = True
                div_status = "Bullish divergence"
            elif delta_oi < 0 and delta_price > 0:
                divergence_detected = True
                div_status = "Bearish divergence"
            else:
                divergence_detected = False
            if price_now != last_price:
                reason_inputs["price_direction"] = "up" if delta_price > 0 else "down"
            if delta_oi != 0:
                reason_inputs["oi_direction"] = "up" if delta_oi > 0 else "down"
        if divergence_detected:
            add_component(
                "divergence",
                points=div_meta.max_points,
                available=True,
                status=div_status,
                note="OI and price moving in opposite directions.",
            )
        else:
            add_component(
                "divergence",
                points=0.0,
                available=True,
                status="No divergence",
                note="",
            )


    if price.get("price") is not None:
        set_state("last_price", price.get("price"))
    if futures.get("aggregated_open_interest") is not None:
        set_state("last_agg_oi", futures.get("aggregated_open_interest"))

    inflow = flows.get("latest_inflow")
    flow_meta = SIGNAL_COMPONENTS.get("whale_flow")
    if inflow is None:
        add_component(
            "whale_flow",
            points=0.0,
            available=False,
            status="XRPL inflow missing",
            note="Redis cache empty; worker may be offline.",
        )
    else:
        flow_scale = _clamp(float(inflow) / 60_000_000)
        flow_points = flow_scale * flow_meta.max_points
        status = "Exchange demand building" if inflow > 10_000_000 else "Muted demand"
        add_component(
            "whale_flow",
            points=flow_points,
            available=True,
            status=status,
            note=f"{float(inflow):,.0f} XRP tagged inflow (capped at 60M)",
        )

    outflow = flows.get("latest_outflow")
    netflow_meta = SIGNAL_COMPONENTS.get("netflow")
    if inflow is None or outflow is None:
        add_component(
            "netflow",
            points=0.0,
            available=False,
            status="Netflow unknown",
            note="Need both inflow and outflow slices to score withdrawals.",
        )
    else:
        withdrawals = max(outflow - inflow, 0.0)
        netflow_scale = _clamp(withdrawals / 100_000_000)
        netflow_points = netflow_scale * netflow_meta.max_points
        status = "Exchanges net-withdrawing" if withdrawals > 0 else "Flat/accumulating"
        add_component(
            "netflow",
            points=netflow_points,
            available=True,
            status=status,
            note=f"{withdrawals:,.0f} XRP 24h net withdrawal bias",
        )
        reason_inputs["netflow_xrp"] = withdrawals if outflow >= inflow else inflow - outflow

    sentiment_ema = sentiment.get("ema")
    sent_meta = SIGNAL_COMPONENTS.get("sentiment")
    if sentiment_ema is None:
        add_component(
            "sentiment",
            points=0.0,
            available=False,
            status="Sentiment cache missing",
            note="Sentiment worker has not populated EMA.",
        )
    else:
        sentiment_scale = _clamp((sentiment_ema - 0.05) / (0.30 - 0.05))
        sentiment_points = sent_meta.max_points * sentiment_scale
        status = "Headline tone supportive" if sentiment_ema >= 0.15 else "Muted tone"
        add_component(
            "sentiment",
            points=sentiment_points,
            available=True,
            status=status,
            note=f"EMA {sentiment_ema:+.2f} vs. +0.05/+0.30 lane",
        )
        reason_inputs["sentiment_ema"] = sentiment_ema

    # Long/short ratio based squeeze component. A value ≤1.0 implies more shorts
    # than longs, favouring a short‑squeeze setup; values ≥2.0 imply longs dominate.
    ls_ratio = futures.get("long_short_ratio")
    squeeze_meta = SIGNAL_COMPONENTS.get("squeeze")
    if ls_ratio is None:
        # When the long/short ratio cannot be fetched (e.g. due to network errors),
        # treat the squeeze setup as neutral rather than punitive. Assign half of
        # the component’s maximum points and mark the input as unavailable.
        default_scale = 0.5
        squeeze_points = squeeze_meta.max_points * default_scale if squeeze_meta else 0.0
        add_component(
            "squeeze",
            points=squeeze_points,
            available=False,
            status="Neutral (L/S ratio unavailable)",
            note="Default neutral weight applied due to missing long/short ratio.",
        )
    else:
        # Linearly scale between 1.0 and 2.0: full points at ≤1.0, zero at ≥2.0.
        ls_scale = _clamp((2.0 - ls_ratio) / (2.0 - 1.0))
        squeeze_points = squeeze_meta.max_points * ls_scale
        status = "Short squeeze risk" if ls_ratio <= 1.0 else "Long‑skewed"
        add_component(
            "squeeze",
            points=squeeze_points,
            available=True,
            status=status,
            note=f"L/S ratio {ls_ratio:.2f}",
        )

    total_points = sum(d["points"] for d in details if d["available"])
    total_cap = sum(d["max_points"] for d in details if d["available"])
    normalized = (total_points / total_cap * 100.0) if total_cap else 0.0
    normalized = min(100.0, max(0.0, normalized))

    log_score_components({d["key"]: d["points"] for d in details})

    return {
        "details": details,
        "composite": normalized,
        "probability": calibrated_conviction_probability(normalized),
        "coverage": total_cap,
        "reason_inputs": reason_inputs,
    }


# =========================
# Data acquisition
# =========================


COINGECKO_BASE = "https://api.coingecko.com/api/v3"
BINANCE_FAPI = "https://fapi.binance.com"
BYBIT_API = "https://api.bybit.com"
REQUEST_TIMEOUT = 12

def fetch_long_short_ratio(period: str = "1h") -> Optional[float]:
    """
    Fetch the global long/short account ratio for XRP futures from Binance.

    Binance exposes a public endpoint for the long/short ratio of each symbol.
    The API is queried without authentication and returns the most recent
    longShortRatio when no start/end timestamps are provided. This signal
    highlights potential short‑squeeze setups: values ≤1.0 indicate that
    shorts dominate long positions.  According to Binance documentation, the
    endpoint accepts the trading pair and a period parameter, and if
    startTime/endTime are omitted the latest data is returned【611834218709811†L84-L110】.

    Parameters
    ----------
    period: str
        The time interval for the ratio; valid values include "5m", "15m",
        "30m", "1h", "2h", "4h", "6h", "12h", and "1d"【611834218709811†L100-L104】.

    Returns
    -------
    Optional[float]
        The numeric long/short ratio, or None if unavailable or on error.
    """
    try:
        url = f"{BINANCE_FAPI}/futures/data/globalLongShortAccountRatio"
        params = {"pair": "XRPUSDT", "period": period, "limit": 1}
        resp = requests.get(url, params=params, timeout=REQUEST_TIMEOUT)
        if resp.ok:
            payload = resp.json()
            if isinstance(payload, list) and payload:
                record = payload[0]
                ratio_str = record.get("longShortRatio")
                if ratio_str is not None:
                    try:
                        return float(ratio_str)
                    except Exception:
                        return None
    except Exception:
        # Ignore transient errors; caller will handle missing data gracefully
        return None
    return None

    # The remainder of this module is unchanged from the upstream file, aside from
    # modifications around the refresh mechanism.  For brevity it is omitted
    # here, but the original logic for data acquisition, presentation, and layout
    # is preserved verbatim.
